# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


                - name: Deploy Github Pages

  uses: ptienchuan/deploy-github-pages-action@1.0.0
  with:
    # [Optional] Determine the directory contains source code. Defaults to "docs"
    source-directory: # optional, default is docs
    # [Optional] Set target branch name for Github Pages. Defaults to "gh-pages"
    target-branch: # optional, default is gh-pages
    # [Optional] Set author of deploying commit. Defaults to ""
    user-name: # optional, default is github-actions[bot]
    # [Optional] Set author of deploying commit. Defaults to ""
    user-email: # optional, default is github-action[bot]@noreply.github.com
          
